          script: |
            cd ~/saleor-deploy
            git pull origin main
            ~/fetch-secrets.sh
            docker compose config -q
            docker compose up -d --remove-orphans
